name: Email Action

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2005235@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      - uses: actions/checkout@v4
